"""add_trade_mode

Revision ID: 0660ab790b8a
Revises: 818dacab6670
Create Date: 2026-01-04 23:18:42.034868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0660ab790b8a"
down_revision: Union[str, None] = "818dacab6670"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("trade_mode", sa.String(), nullable=True))
    op.add_column("settings", sa.Column("decision_engine_enabled", sa.Boolean(), nullable=True))
    op.add_column("settings", sa.Column("decision_threshold", sa.Integer(), nullable=True))
    op.add_column("settings", sa.Column("fees_bps", sa.Integer(), nullable=True))
    op.add_column("settings", sa.Column("slippage_bps", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "slippage_bps")
    op.drop_column("settings", "fees_bps")
    op.drop_column("settings", "decision_threshold")
    op.drop_column("settings", "decision_engine_enabled")
    op.drop_column("settings", "trade_mode")
    # ### end Alembic commands ###
