"""numeric_precision_and_broker_id

Revision ID: 818dacab6670
Revises: 001_initial_schema
Create Date: 2026-01-02 23:28:35.003091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "818dacab6670"
down_revision: Union[str, None] = "001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("broker_id", sa.String(), nullable=True))
    op.alter_column(
        "orders",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "filled_qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.add_column("positions", sa.Column("broker_id", sa.String(), nullable=True))
    op.alter_column(
        "positions",
        "qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "avg_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "sl",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "tp",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "unrealized_pnl",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "realized_pnl",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=True,
    )
    op.alter_column(
        "settings",
        "risk_per_trade_pct",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "settings",
        "daily_loss_limit_pct",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "settings",
        "rr_target",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.add_column("signals", sa.Column("broker_id", sa.String(), nullable=True))
    op.alter_column(
        "signals",
        "entry",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "sl",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "tp",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "size",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "r",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.add_column("trades", sa.Column("broker_id", sa.String(), nullable=True))
    op.alter_column(
        "trades",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=9),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades",
        "qty",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "trades",
        "price",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("trades", "broker_id")
    op.alter_column(
        "signals",
        "r",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "size",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "tp",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "sl",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "signals",
        "entry",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("signals", "broker_id")
    op.alter_column(
        "settings",
        "rr_target",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "settings",
        "daily_loss_limit_pct",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "settings",
        "risk_per_trade_pct",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "realized_pnl",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "unrealized_pnl",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "tp",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "sl",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "avg_price",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "positions",
        "qty",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("positions", "broker_id")
    op.alter_column(
        "orders",
        "filled_qty",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "qty",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "price",
        existing_type=sa.Numeric(precision=18, scale=9),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("orders", "broker_id")
    # ### end Alembic commands ###
